### ISSUE TITLE
light-online firing incorrectly

### ISSUE THREAD

**Issue by amk221** [MariusRumpf/node-lifx#68]
I have some code which detects when a light comes online, and its kelvin and brightness are set based on a predetermined config.

Perhaps since an iOS app update, or maybe even a light firmware update, now - whenever I interact with the app, say for example to change a light brightness - the `light-online` event fires. (Even though it was already online).

...meaning that my code runs (when it shouldn't be). And the brightness I just chose with the app, is then overridden.

**Comment by ristomatti** [comment]
Since this repo has been inactive for quite some time I am afraid you'll need to workaround the issue within your code somehow. Or perhaps send feedback to LIFX through the app. The support has been quite responsive at times. I've got a bunch of feature requests implemented/bugs fixed on the Android app at least.

I'd be curious to know though which light type was this? I've recently got couple of GU10 downlights, four pack of Mini Day & Dusk and a Tile set. I haven't noticed this behavior myself yet at least. Previously I've already got E27 lamps of 2-3 different generations and some LIFX-Z strips, totalling to 17 devices.

As an off-topic note, I've noticed the Android app getting quite laggy with this amount of lights when adjusting all the lights at the same time. I've sent a bug report about this.

**Comment by amk221** [comment]
Thanks for the quick response! 

The problematic one is an A19 (A60).
My Mini Day & Dusk's are fine.

I've since narrowed it down to not-the-app. 
It could just be a dud bulb, although it's new behaviour. Cheers anyway!
